---
title: Triple Sided
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
exclude:
- node_modules
- gulpfile.js
- package.json
- preview.jpg
- README.md
- s3_website.yml
url: http://www.triple-sided.com
gems:
- jekyll-paginate-v2
baseurl: "/"
permalink: "/:categories/:title/"
compress_html:
  clippings: all
  comments:
  - "<!-- "
  - " -->"
  endings: all
pagination:
  enabled: true
  debug: false
  collection: posts
  per_page: 5
  permalink: "/page/:num/"
  limit: 0
