name: Ben Franzoso
markdown: redcarpet
exclude: ["node_modules",
  "gulpfile.js",
  "package.json",
  "preview.jpg",
  "README.md"]

url: "http://www.triple-sided.com"
permalink: /:categories/:title/

# Files
