name: Ben Franzoso
exclude: ["node_modules",
  "gulpfile.js",
  "package.json",
  "preview.jpg",
  "README.md"]

url: "http://www.triple-sided.com"

gems:
  - jekyll-paginate-v2

# Pagination
pagination:
  enabled: true
  per_page: 1
  permalink: '/page/:num/'
